### ISSUE TITLE
Provide auxiliary packages in order the project to be able to compile

### ISSUE THREAD

**Issue by firephil** [johnalexandergreene/Forsythia#4]
![forsynthia](https://user-images.githubusercontent.com/698336/115487454-67af4800-a261-11eb-86cd-7fe6d9338258.png)

thank you

**Comment by johnalexandergreene** [comment]
geom kisrhombille is at https://github.com/johnalexandergreene/Geom_Kisrhombille

**Comment by firephil** [comment]
The project directory structure is not correct, and there are packages missing  Geom_Kisrhombille, org.fleen.util i managed to extract them from the runnable jar and add them as a util.jar but upon loading the grammars at the start of GE class FJig is not compatible Jig class which the grammars where generated and i get a cast error.

If you could provide a compilable project it would be great.

I hacked around the jars and managed to produce a working project in Netbeans but the source version  with the grammars are not in synch. FJig vs Jig classes i guess Jig is an older version ?
